### ISSUE TITLE
No error handling in qa_chain.invoke in 01_naive_rag

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAP-samples/btp-genai-starter-kit#83]
See the following trace returned when the model does not respond before the timeout when called via `result = qa_chain.invoke({"question": question})`, in case you want to add any error handling.

```
$ poetry run python main.py 
Welcome to the interactive Q&A session

0: Clean up database
1: Ingest data
2: Retrieve data
3: Exit

Which task would you like to run?2
Ask a question or type 'exit' to leave: Who can contribute?
[2024-08-01 15:01:23] INFO   : Asking a question: Who can contribute?
[2024-08-01 15:01:53] INFO   : Retrying request to %s in %f seconds
[2024-08-01 15:01:54] INFO   : Retrying request to %s in %f seconds
[2024-08-01 15:01:56] ERROR  : Traceback (most recent call last):

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/scripts/step03_explore_examples/01_naive_rag/main.py", line 81, in <module>
    main()

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/scripts/step03_explore_examples/01_naive_rag/main.py", line 71, in main
    chat()

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/scripts/step03_explore_examples/01_naive_rag/main.py", line 29, in chat
    result = qa_chain.invoke({"question": question})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 166, in invoke
    raise e

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/conversational_retrieval/base.py", line 168, in _call
    answer = self.combine_docs_chain.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 605, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 383, in __call__
    return self.invoke(
           ^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 166, in invoke
    raise e

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 138, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py", line 245, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 318, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 383, in __call__
    return self.invoke(
           ^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 166, in invoke
    raise e

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 128, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 140, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 698, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 555, in generate
    raise e

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 545, in generate
    self._generate_with_cache(

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 770, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 549, in _generate
    response = self.client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/gen_ai_hub/proxy/native/openai/clients.py", line 288, in create
    return super().create(messages=messages, model=model_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
           ^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/gen_ai_hub/proxy/native/openai/clients.py", line 505, in request
    return super().request(cast_to, options, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
           ^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1031, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1079, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1031, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1079, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

NoneType: None
[2024-08-01 15:01:56] ERROR  :   File "/home/user/projects/btp-genai-starter-kit/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None

NoneType: None
[2024-08-01 15:01:56] ERROR  : openai.RateLimitError: Error code: 429 - {'error': 'TooManyRequest', 'message': 'Your request has been rate limited. Please try again later.'}

NoneType: None
[2024-08-01 15:01:56] ERROR  : Error code: 429 - {'error': 'TooManyRequest', 'message': 'Your request has been rate limited. Please try again later.'}
NoneType: None
```

**Comment by EvgeniiSkrebtcov** [comment]
@Sygyzmundovych, thank you for submitting. I'll give it a look and add proper error / rate limit handling.
